// ============ aggregated from ops_recurrent_gdn.cpp ============
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {

namespace {

typedef struct aclOpExecutor aclOpExecutor;

// aclnnRecurrentGatedDeltaRuleGetWorkspaceSize(
//   query, key, value, beta, state, actual_seq_lengths, ssm_state_indices,
//   g, gk, num_accepted_tokens, float scale, out, &ws_size, &executor)
using GetWorkspaceFn = int (*)(const aclTensor*, const aclTensor*,
                               const aclTensor*, const aclTensor*,
                               const aclTensor*, const aclTensor*,
                               const aclTensor*, const aclTensor*,
                               const aclTensor*, const aclTensor*, float,
                               const aclTensor*, uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);

void add_view(std::vector<std::unique_ptr<AclTensorView>>& views,
              const at::Tensor& t) {
  views.push_back(std::make_unique<AclTensorView>(t));
}

void add_view(std::vector<std::unique_ptr<AclTensorView>>& views,
              const c10::optional<at::Tensor>& t) {
  add_view(views, t.has_value() && t->defined() ? *t : at::Tensor());
}

}  // namespace

at::Tensor npu_recurrent_gated_delta_rule(
    const at::Tensor& query,
    const at::Tensor& key,
    const at::Tensor& value,
    at::Tensor& state,
    const c10::optional<at::Tensor>& beta,
    double scale,
    const c10::optional<at::Tensor>& actual_seq_lengths,
    const c10::optional<at::Tensor>& ssm_state_indices,
    const c10::optional<at::Tensor>& num_accepted_tokens,
    const c10::optional<at::Tensor>& g,
    const c10::optional<at::Tensor>& gk,
    uint64_t stream) {
  auto output = at::empty(value.sizes(),
                          value.options().dtype(at::kBFloat16));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(12);
  add_view(views, query);
  add_view(views, key);
  add_view(views, value);
  add_view(views, beta);
  add_view(views, state);
  add_view(views, actual_seq_lengths);
  add_view(views, ssm_state_indices);
  add_view(views, g);
  add_view(views, gk);
  add_view(views, num_accepted_tokens);
  add_view(views, output);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<GetWorkspaceFn>(
      rt.symbol("aclnnRecurrentGatedDeltaRuleGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(
      rt.symbol("aclnnRecurrentGatedDeltaRule"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(), views[1]->get(), views[2]->get(), views[3]->get(),
      views[4]->get(), views[5]->get(), views[6]->get(), views[7]->get(),
      views[8]->get(), views[9]->get(), static_cast<float>(scale),
      views[10]->get(), &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0,
              "aclnnRecurrentGatedDeltaRuleGetWorkspaceSize failed: ",
              get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty(
        {static_cast<int64_t>(workspace_size)},
        at::TensorOptions().dtype(at::kByte).device(value.device()));
    workspace_ptr = workspace.data_ptr();
  }

  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0,
              "aclnnRecurrentGatedDeltaRule failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin
// ============ aggregated from ops_kda_gate_cumsum.cpp ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnKdaGateCumsum
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_kda_gate_cumsum_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    int64_t,
    bool,
    bool,
    double,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_kda_gate_cumsum(
    const at::Tensor& g,
    const c10::optional<at::Tensor>& A_log,
    const c10::optional<at::Tensor>& dt_bias,
    const std::vector<int64_t>& cu_seqlens,
    int64_t chunk_size,
    bool use_gate_in_kernel,
    bool safe_gate,
    double lower_bound,
    uint64_t stream) {
  auto output = at::empty(g.sizes(), g.options().dtype(at::kFloat));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(A_log.has_value() && A_log->defined() ? *A_log : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(dt_bias.has_value() && dt_bias->defined() ? *dt_bias : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_kda_gate_cumsum_GetWorkspaceFn>(rt.symbol("aclnnKdaGateCumsumGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnKdaGateCumsum"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      cu_seqlens_view.get(),
      chunk_size,
      use_gate_in_kernel,
      safe_gate,
      lower_bound,
      views[3]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnKdaGateCumsumGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(g.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnKdaGateCumsum failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin
// ============ aggregated from ops_npu_chunk_local_cumsum.cpp ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnChunkLocalCumsum
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_chunk_local_cumsum_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    bool,
    double,
    bool,
    const char*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_chunk_local_cumsum(
    const at::Tensor& g,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    bool reverse,
    double scale,
    bool head_first,
    const std::string& output_dtype,
    uint64_t stream) {
  auto output = at::empty(g.sizes(), g.options().dtype(at::kFloat));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_chunk_local_cumsum_GetWorkspaceFn>(rt.symbol("aclnnChunkLocalCumsumGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnChunkLocalCumsum"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      reverse,
      scale,
      head_first,
      output_dtype.c_str(),
      views[1]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnChunkLocalCumsumGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(g.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnChunkLocalCumsum failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin

// ============ generated from aclnnChunkScaledDotKkt ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnChunkScaledDotKkt
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_chunk_scaled_dot_kkt_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_chunk_scaled_dot_kkt(
    const at::Tensor& k,
    const at::Tensor& g,
    const at::Tensor& beta,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    uint64_t stream) {
  auto output = at::empty({k.size(0), g.size(1), k.size(2), chunk_size}, k.options().dtype(at::kFloat));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(beta));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_chunk_scaled_dot_kkt_GetWorkspaceFn>(rt.symbol("aclnnChunkScaledDotKktGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnChunkScaledDotKkt"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      views[3]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnChunkScaledDotKktGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(g.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnChunkScaledDotKkt failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnSolveTri ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnSolveTri
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_solve_tri_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    const char*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_solve_tri(
    const at::Tensor& x,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    const std::string& layout,
    uint64_t stream) {
  auto output = at::empty_like(x);

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(x, true, true));
  views.push_back(std::make_unique<AclTensorView>(output, true, true));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_solve_tri_GetWorkspaceFn>(rt.symbol("aclnnSolveTriGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnSolveTri"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      layout.c_str(),
      views[1]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnSolveTriGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(x.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnSolveTri failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin



// ============ generated from aclnnRecomputeWUFwd ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnRecomputeWUFwd
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_recompute_w_u_fwd_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

std::vector<at::Tensor> npu_recompute_w_u_fwd(
    const at::Tensor& k,
    const at::Tensor& v,
    const at::Tensor& beta,
    const at::Tensor& A,
    const c10::optional<at::Tensor>& g,
    const c10::optional<at::Tensor>& gk,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    uint64_t stream) {
  std::vector<at::Tensor> outputs;
  outputs.push_back(at::empty({v.size(0), v.size(1), v.size(2), k.size(3)}, k.options()));
  outputs.push_back(at::empty_like(v));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(v));
  views.push_back(std::make_unique<AclTensorView>(beta));
  views.push_back(std::make_unique<AclTensorView>(A));
  views.push_back(std::make_unique<AclTensorView>(g.has_value() && g->defined() ? *g : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(gk.has_value() && gk->defined() ? *gk : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(outputs[0]));
  views.push_back(std::make_unique<AclTensorView>(outputs[1]));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_recompute_w_u_fwd_GetWorkspaceFn>(rt.symbol("aclnnRecomputeWUFwdGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnRecomputeWUFwd"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      views[6]->get(),
      views[7]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnRecomputeWUFwdGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(k.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnRecomputeWUFwd failed: ", launch_ret);
  return outputs;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnPrepareWyReprBwdFull ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnPrepareWyReprBwdFull
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_prepare_wy_repr_bwd_full_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

std::vector<at::Tensor> npu_prepare_wy_repr_bwd_full(
    const at::Tensor& k,
    const at::Tensor& v,
    const at::Tensor& beta,
    const at::Tensor& A,
    const at::Tensor& dA,
    const at::Tensor& dw,
    const at::Tensor& du,
    const at::Tensor& g,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    uint64_t stream) {
  std::vector<at::Tensor> outputs;
  outputs.push_back(at::empty_like(k));
  outputs.push_back(at::empty_like(v));
  outputs.push_back(at::empty_like(beta));
  outputs.push_back(at::empty_like(g));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(v));
  views.push_back(std::make_unique<AclTensorView>(beta));
  views.push_back(std::make_unique<AclTensorView>(A));
  views.push_back(std::make_unique<AclTensorView>(dA));
  views.push_back(std::make_unique<AclTensorView>(dw));
  views.push_back(std::make_unique<AclTensorView>(du));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(outputs[0]));
  views.push_back(std::make_unique<AclTensorView>(outputs[1]));
  views.push_back(std::make_unique<AclTensorView>(outputs[2]));
  views.push_back(std::make_unique<AclTensorView>(outputs[3]));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_prepare_wy_repr_bwd_full_GetWorkspaceFn>(rt.symbol("aclnnPrepareWyReprBwdFullGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnPrepareWyReprBwdFull"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      views[6]->get(),
      views[7]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      views[8]->get(),
      views[9]->get(),
      views[10]->get(),
      views[11]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnPrepareWyReprBwdFullGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(k.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnPrepareWyReprBwdFull failed: ", launch_ret);
  return outputs;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnPrepareWyReprBwd ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnPrepareWyReprBwd
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_prepare_wy_repr_bwd_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

std::vector<at::Tensor> npu_prepare_wy_repr_bwd(
    const at::Tensor& k,
    const at::Tensor& v,
    const at::Tensor& beta,
    const at::Tensor& A,
    const at::Tensor& dw,
    const at::Tensor& du,
    const at::Tensor& g,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    uint64_t stream) {
  std::vector<at::Tensor> outputs;
  outputs.push_back(at::empty_like(k));
  outputs.push_back(at::empty_like(v));
  outputs.push_back(at::empty_like(beta));
  outputs.push_back(at::empty_like(g));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(v));
  views.push_back(std::make_unique<AclTensorView>(beta));
  views.push_back(std::make_unique<AclTensorView>(A));
  views.push_back(std::make_unique<AclTensorView>(dw));
  views.push_back(std::make_unique<AclTensorView>(du));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(outputs[0]));
  views.push_back(std::make_unique<AclTensorView>(outputs[1]));
  views.push_back(std::make_unique<AclTensorView>(outputs[2]));
  views.push_back(std::make_unique<AclTensorView>(outputs[3]));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_prepare_wy_repr_bwd_GetWorkspaceFn>(rt.symbol("aclnnPrepareWyReprBwdGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnPrepareWyReprBwd"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      views[6]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      views[7]->get(),
      views[8]->get(),
      views[9]->get(),
      views[10]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnPrepareWyReprBwdGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(k.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnPrepareWyReprBwd failed: ", launch_ret);
  return outputs;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnChunkBwdDvLocal ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnChunkBwdDvLocal
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_chunk_bwd_dv_local_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    double,
    int64_t,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_chunk_bwd_dv_local(
    const at::Tensor& q,
    const at::Tensor& k,
    const at::Tensor& d_o,
    const at::Tensor& g,
    const c10::optional<at::Tensor>& g_gamma,
    const c10::optional<at::Tensor>& A,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    double scale,
    int64_t chunk_size,
    uint64_t stream) {
  at::Tensor output = at::empty_like(d_o);

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(q));
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(d_o));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(g_gamma.has_value() && g_gamma->defined() ? *g_gamma : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(A.has_value() && A->defined() ? *A : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_chunk_bwd_dv_local_GetWorkspaceFn>(rt.symbol("aclnnChunkBwdDvLocalGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnChunkBwdDvLocal"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      scale,
      chunk_size,
      views[6]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnChunkBwdDvLocalGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(q.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnChunkBwdDvLocal failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnPrepareWyReprBwdDa ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnPrepareWyReprBwdDa
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_prepare_wy_repr_bwd_da_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_prepare_wy_repr_bwd_da(
    const at::Tensor& k,
    const at::Tensor& v,
    const at::Tensor& beta,
    const at::Tensor& A,
    const at::Tensor& dw,
    const at::Tensor& du,
    const at::Tensor& g,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    uint64_t stream) {
  at::Tensor output = at::empty_like(A);

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(v));
  views.push_back(std::make_unique<AclTensorView>(beta));
  views.push_back(std::make_unique<AclTensorView>(A));
  views.push_back(std::make_unique<AclTensorView>(dw));
  views.push_back(std::make_unique<AclTensorView>(du));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_prepare_wy_repr_bwd_da_GetWorkspaceFn>(rt.symbol("aclnnPrepareWyReprBwdDaGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnPrepareWyReprBwdDa"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      views[6]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      views[7]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnPrepareWyReprBwdDaGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(k.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnPrepareWyReprBwdDa failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnFastGelu ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnFastGelu
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_fast_gelu_custom_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_fast_gelu_custom(
    const at::Tensor& self,
    uint64_t stream) {
  at::Tensor output = at::empty_like(self);

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(self));
  views.push_back(std::make_unique<AclTensorView>(output));

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_fast_gelu_custom_GetWorkspaceFn>(rt.symbol("aclnnFastGeluGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnFastGelu"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnFastGeluGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(self.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnFastGelu failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnFastGeluBackward ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnFastGeluBackward
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_fast_gelu_custom_backward_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_fast_gelu_custom_backward(
    const at::Tensor& grad,
    const at::Tensor& self,
    uint64_t stream) {
  at::Tensor output = at::empty_like(grad);

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(grad));
  views.push_back(std::make_unique<AclTensorView>(self));
  views.push_back(std::make_unique<AclTensorView>(output));

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_fast_gelu_custom_backward_GetWorkspaceFn>(rt.symbol("aclnnFastGeluBackwardGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnFastGeluBackward"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnFastGeluBackwardGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(grad.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnFastGeluBackward failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin


// ============ generated from aclnnChunkBwdDqkwg ============

// ============ generated from aclnnChunkBwdDqkwg ============
// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnChunkBwdDqkwg
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_chunk_bwd_dqkwg_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    const aclTensor*,
    const aclTensor*,
    float,
    int64_t,
    bool,
    bool,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

std::vector<at::Tensor> npu_chunk_bwd_dqkwg(
    const at::Tensor& q,
    const at::Tensor& k,
    const at::Tensor& v,
    const at::Tensor& g,
    const at::Tensor& h,
    const at::Tensor& dox,
    const at::Tensor& dh,
    const at::Tensor& dv,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    const c10::optional<at::Tensor>& w,
    const c10::optional<at::Tensor>& g_gamma,
    float scale,
    int64_t chunk_size,
    bool use_exp2,
    bool transpose_state_layout,
    uint64_t stream) {
  std::vector<at::Tensor> outputs;
  outputs.push_back(at::empty_like(q));
  outputs.push_back(at::empty_like(k));
  outputs.push_back(at::empty({q.size(0), v.size(1), q.size(2), q.size(3)}, q.options()));
  outputs.push_back(at::empty_like(g));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(q));
  views.push_back(std::make_unique<AclTensorView>(k));
  views.push_back(std::make_unique<AclTensorView>(v));
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(h));
  views.push_back(std::make_unique<AclTensorView>(dox));
  views.push_back(std::make_unique<AclTensorView>(dh));
  views.push_back(std::make_unique<AclTensorView>(dv));
  views.push_back(std::make_unique<AclTensorView>(w.has_value() && w->defined() ? *w : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(g_gamma.has_value() && g_gamma->defined() ? *g_gamma : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(outputs[0]));
  views.push_back(std::make_unique<AclTensorView>(outputs[1]));
  views.push_back(std::make_unique<AclTensorView>(outputs[2]));
  views.push_back(std::make_unique<AclTensorView>(outputs[3]));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_chunk_bwd_dqkwg_GetWorkspaceFn>(rt.symbol("aclnnChunkBwdDqkwgGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnChunkBwdDqkwg"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      views[3]->get(),
      views[4]->get(),
      views[5]->get(),
      views[6]->get(),
      views[7]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      views[8]->get(),
      views[9]->get(),
      scale,
      chunk_size,
      use_exp2,
      transpose_state_layout,
      views[10]->get(),
      views[11]->get(),
      views[12]->get(),
      views[13]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnChunkBwdDqkwgGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(q.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnChunkBwdDqkwg failed: ", launch_ret);
  return outputs;
}

}  // namespace fla_npu_thin

