// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnKdaGateCumsum
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_kda_gate_cumsum_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclTensor*,
    const aclTensor*,
    const aclIntArray*,
    int64_t,
    bool,
    bool,
    double,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_kda_gate_cumsum(
    const at::Tensor& g,
    const c10::optional<at::Tensor>& A_log,
    const c10::optional<at::Tensor>& dt_bias,
    const std::vector<int64_t>& cu_seqlens,
    int64_t chunk_size,
    bool use_gate_in_kernel,
    bool safe_gate,
    double lower_bound,
    uint64_t stream) {
  auto output = at::empty(g.sizes(), g.options().dtype(at::kFloat));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(A_log.has_value() && A_log->defined() ? *A_log : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(dt_bias.has_value() && dt_bias->defined() ? *dt_bias : at::Tensor()));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_kda_gate_cumsum_GetWorkspaceFn>(rt.symbol("aclnnKdaGateCumsumGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnKdaGateCumsum"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      views[1]->get(),
      views[2]->get(),
      cu_seqlens_view.get(),
      chunk_size,
      use_gate_in_kernel,
      safe_gate,
      lower_bound,
      views[3]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnKdaGateCumsumGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(g.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnKdaGateCumsum failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin
