// Generated by op_spec_codegen.py — do not edit by hand.
// spec: aclnnChunkLocalCumsum
#include <ATen/ATen.h>
#include <torch/extension.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "thin_launcher/runtime.h"
#include "thin_launcher/tensor_desc.h"

namespace fla_npu_thin {
namespace {
typedef struct aclOpExecutor aclOpExecutor;

using npu_chunk_local_cumsum_GetWorkspaceFn = int (*)(
    const aclTensor*,
    const aclIntArray*,
    const aclIntArray*,
    int64_t,
    bool,
    double,
    bool,
    const char*,
    const aclTensor*,
    uint64_t*, aclOpExecutor**);
using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);
}  // namespace

at::Tensor npu_chunk_local_cumsum(
    const at::Tensor& g,
    const std::vector<int64_t>& cu_seqlens,
    const std::vector<int64_t>& chunk_indices,
    int64_t chunk_size,
    bool reverse,
    double scale,
    bool head_first,
    const std::string& output_dtype,
    uint64_t stream) {
  auto output = at::empty(g.sizes(), g.options().dtype(at::kFloat));

  std::vector<std::unique_ptr<AclTensorView>> views;
  views.reserve(8);
  views.push_back(std::make_unique<AclTensorView>(g));
  views.push_back(std::make_unique<AclTensorView>(output));
  AclIntArrayView cu_seqlens_view(cu_seqlens);
  AclIntArrayView chunk_indices_view(chunk_indices);

  auto& rt = Runtime::instance();
  auto get_ws = reinterpret_cast<npu_chunk_local_cumsum_GetWorkspaceFn>(rt.symbol("aclnnChunkLocalCumsumGetWorkspaceSize"));
  auto launch = reinterpret_cast<LaunchFn>(rt.symbol("aclnnChunkLocalCumsum"));

  uint64_t workspace_size = 0;
  aclOpExecutor* executor = nullptr;
  const int get_ret = get_ws(
      views[0]->get(),
      cu_seqlens_view.get(),
      chunk_indices_view.get(),
      chunk_size,
      reverse,
      scale,
      head_first,
      output_dtype,
      views[1]->get(),
      &workspace_size, &executor);
  TORCH_CHECK(get_ret == 0, "aclnnChunkLocalCumsumGetWorkspaceSize failed: ", get_ret);

  void* workspace_ptr = nullptr;
  at::Tensor workspace;
  if (workspace_size != 0) {
    workspace = at::empty({static_cast<int64_t>(workspace_size)},
                          at::TensorOptions().dtype(at::kByte).device(g.device()));
    workspace_ptr = workspace.data_ptr();
  }
  const int launch_ret =
      launch(workspace_ptr, workspace_size, executor,
             reinterpret_cast<void*>(stream));
  TORCH_CHECK(launch_ret == 0, "aclnnChunkLocalCumsum failed: ", launch_ret);
  return output;
}

}  // namespace fla_npu_thin
