/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * BSD 3-Clause License.
 *
 * ChunkKdaFwdIntraSubChunk — shared definitions (BNSD + optional TND varlen, GVA).
 *
 * MIX_AIC_1_2 lockstep pipeline (DESIGN §4 first milestone):
 *   stage_0 Vector : Qg, W(=Kgq), Kg  → scoreWs   (gate in fp32, cast to qk dtype)
 *   stage_1 Cube   : Aqk_raw = Qg@Kg.T ; Akk_raw = W@Kg.T  → cmatWs (fp32)
 *   stage_1 Vector : tril/scale (Aqk) ; strict_tril*beta (L) ; Forward-Substitution
 *                    Akkd = (I+L)^{-1} ; store Aqk diag block + Akkd
 *
 * Forward Substitution (NOT MCH) — vector-only row updates on AIV.
 */

#ifndef CHUNK_KDA_FWD_INTRA_SUB_CHUNK_COMMON_H
#define CHUNK_KDA_FWD_INTRA_SUB_CHUNK_COMMON_H

#include "kernel_operator.h"

#if defined(__CCE_AICORE__) && __CCE_AICORE__ == 310
#define CATLASS_ARCH 3510
#else
#define CATLASS_ARCH 2201
#endif
#include "catlass/arch/arch.hpp"
#include "catlass/arch/resource.hpp"
#include "catlass/catlass.hpp"
#include "catlass/gemm/block/block_mmad.hpp"
#include "catlass/gemm/dispatch_policy.hpp"
#include "catlass/gemm/gemm_type.hpp"
#include "catlass/gemm/tile/tile_copy.hpp"
#include "catlass/gemm/tile/tile_mmad.hpp"
#include "catlass/gemm_coord.hpp"
#include "catlass/layout/layout.hpp"
#include "catlass/arch/cross_core_sync.hpp"
#include "tla/layout.hpp"
#include "tla/tensor.hpp"

#ifndef TORCH_MODE
#include "lib/matmul_intf.h"
#endif

// NOTE: TilingData struct (ChunkKdaFwdIntraSubChunkTilingData) is auto-generated by
// the ascendc build via GET_TILING_DATA in the .cpp entry; do NOT include op_host tiling.h
// here (it is not on the kernel include path).

using namespace AscendC;

namespace kda_isub {

using _16 = tla::Int<16>;
using _128 = tla::Int<128>;

constexpr float LN2 = 0.6931471805599453f;
constexpr float EXP2_CLAMP = 80.0f;
constexpr float EXP_INPUT_MAX = EXP2_CLAMP * LN2;
constexpr float EXP_INPUT_MIN = -EXP2_CLAMP * LN2;
constexpr float FP16_MAX = 65504.0f;
constexpr uint32_t MAX_K = 256;
constexpr uint32_t MAX_BC = 16;
constexpr uint32_t MAX_BT = 128;

constexpr uint32_t SCORE_PLANES = 3;
constexpr uint32_t C_PLANES = 2;
constexpr uint32_t PLANE_QG = 0; // Qg = q * gq
constexpr uint32_t PLANE_W = 1;  // W  = Kgq = k * gq
constexpr uint32_t PLANE_KG = 2; // Kg = k * gk
constexpr uint32_t PLANE_AQK = 0;
constexpr uint32_t PLANE_AKK = 1;

// UB HardEvent ids (kept clear of Catlass BlockMmad priming on 0/1).
constexpr uint32_t EVT_MTE2_V = 0;
constexpr uint32_t EVT_V_S = 4;
constexpr uint32_t EVT_S_V = 5;
constexpr uint32_t EVT_V_MTE3 = 6;
constexpr uint32_t EVT_MTE3_V = 7;
constexpr uint32_t EVT_MTE3_MTE2 = 3;

// Cross-core flags (AIC <-> AIV pair). Even ids per convention.
constexpr uint8_t FLAG_S0_READY = 4; // AIV → AIC : scoreWs slot filled
constexpr uint8_t FLAG_CUBE_DONE = 2; // AIC → AIV : cmatWs slot filled

#if defined(__CCE_AICORE__) && __CCE_AICORE__ == 310
using KdaArchTag = Catlass::Arch::Ascend950;
#else
using KdaArchTag = Catlass::Arch::AtlasA2;
#endif
using KdaDispatchPolicy = Catlass::Gemm::MmadPingpong<KdaArchTag, true, false>;
using KdaL1TileShape = tla::Shape<_16, _16, _128>;
using KdaL0TileShape = KdaL1TileShape;

// ---------------------------------------------------------------------------
// Shared base: GM buffers, tiling scalars, addressing, copy helpers.
// ---------------------------------------------------------------------------
template <typename T>
class KdaSubChunkBase {
public:
    __aicore__ inline void InitCommon(GM_ADDR q, GM_ADDR k, GM_ADDR g, GM_ADDR beta, GM_ADDR cuSeqlens,
                                      GM_ADDR chunkIndices, GM_ADDR aqk, GM_ADDR akkd, GM_ADDR userWS,
                                      const ChunkKdaFwdIntraSubChunkTilingData &tiling)
    {
        q_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(q));
        k_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(k));
        g_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(g));
        beta_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(beta));
        if (cuSeqlens != nullptr) {
            cuSeqlens_.SetGlobalBuffer(reinterpret_cast<__gm__ int64_t *>(cuSeqlens));
        }
        if (chunkIndices != nullptr) {
            chunkIndices_.SetGlobalBuffer(reinterpret_cast<__gm__ int64_t *>(chunkIndices));
        }
        aqk_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(aqk));
        akkd_.SetGlobalBuffer(reinterpret_cast<__gm__ float *>(akkd));
        scoreWs_.SetGlobalBuffer(reinterpret_cast<__gm__ T *>(userWS));
        cmatWs_.SetGlobalBuffer(reinterpret_cast<__gm__ float *>(userWS + tiling.scoreScratchBytes));

        batch_ = static_cast<uint64_t>(tiling.batch);
        t_ = static_cast<uint64_t>(tiling.t);
        h_ = static_cast<uint64_t>(tiling.h);
        hv_ = static_cast<uint64_t>(tiling.hv);
        kDim_ = static_cast<uint64_t>(tiling.k);
        bt_ = static_cast<uint64_t>(tiling.chunkSize);
        bc_ = static_cast<uint64_t>(tiling.subChunkSize);
        nc_ = static_cast<uint64_t>(tiling.numSubChunks);
        totalTasks_ = static_cast<uint64_t>(tiling.totalTasks);
        usedCoreNum_ = static_cast<uint64_t>(tiling.usedCoreNum);
        depth_ = static_cast<uint64_t>(tiling.scoreQueueDepth);
        if (depth_ == 0) {
            depth_ = 2;
        }
        hasVarlen_ = tiling.hasCuSeqlens != 0;
        scale_ = tiling.scale;
        group_ = (h_ == 0) ? 1 : (hv_ / h_);
    }

    __aicore__ inline bool ValidShapes() const
    {
        return !(usedCoreNum_ == 0 || totalTasks_ == 0 || kDim_ == 0 || bc_ != MAX_BC || kDim_ > MAX_K || h_ == 0 ||
                 hv_ == 0 || hv_ < h_ || (hv_ % h_) != 0);
    }

protected:
    __aicore__ inline uint64_t QkRowOff(uint64_t b, uint64_t h, uint64_t tok) const
    {
        return ((b * h_ + h) * t_ + tok) * kDim_;
    }
    __aicore__ inline uint64_t HvRowOff(uint64_t b, uint64_t hv, uint64_t tok) const
    {
        return ((b * hv_ + hv) * t_ + tok) * kDim_;
    }
    __aicore__ inline uint64_t BetaOff(uint64_t b, uint64_t hv, uint64_t tok) const
    {
        return (b * hv_ + hv) * t_ + tok;
    }
    __aicore__ inline uint64_t AqkOff(uint64_t b, uint64_t hv, uint64_t tok, uint64_t col) const
    {
        return ((b * hv_ + hv) * t_ + tok) * bt_ + col;
    }
    __aicore__ inline uint64_t AkkdOff(uint64_t b, uint64_t hv, uint64_t tok) const
    {
        return ((b * hv_ + hv) * t_ + tok) * bc_;
    }
    __aicore__ inline uint64_t ScoreOff(uint64_t slot, uint64_t plane, uint64_t row, uint64_t d = 0) const
    {
        return (((coreIdx_ * depth_ + slot) * SCORE_PLANES + plane) * bc_ + row) * kDim_ + d;
    }
    __aicore__ inline uint64_t CmatOff(uint64_t slot, uint64_t plane, uint64_t row = 0, uint64_t col = 0) const
    {
        return (((coreIdx_ * depth_ + slot) * C_PLANES + plane) * bc_ + row) * bc_ + col;
    }
    __aicore__ inline uint64_t SlotOf(uint64_t iSub) const
    {
        return iSub % depth_;
    }

    // task = iChunk * (batch*hv) + iB*hv + iHv
    __aicore__ inline void DecodeTask(uint64_t task, uint64_t &iB, uint64_t &iHv, uint64_t &iH, uint64_t &iChunk) const
    {
        const uint64_t bhv = batch_ * hv_;
        const uint64_t iBhv = task % bhv;
        iChunk = task / bhv;
        iB = iBhv / hv_;
        iHv = iBhv % hv_;
        iH = iHv / group_;
    }

    // AIC path: chunkIndices/cuSeqlens read via scalar GetValue (no UB). AIV path: LoadI64.
    __aicore__ inline void ResolveChunkScalar(uint64_t iChunk, uint64_t iB, uint64_t &bos, uint64_t &localT,
                                              uint64_t &localChunk, uint64_t &bIdx) const
    {
        bos = 0;
        localT = t_;
        localChunk = iChunk;
        bIdx = iB;
        if (hasVarlen_) {
            const uint64_t seqId = static_cast<uint64_t>(chunkIndices_.GetValue(iChunk * 2));
            localChunk = static_cast<uint64_t>(chunkIndices_.GetValue(iChunk * 2 + 1));
            bos = static_cast<uint64_t>(cuSeqlens_.GetValue(seqId));
            const uint64_t eos = static_cast<uint64_t>(cuSeqlens_.GetValue(seqId + 1));
            localT = eos - bos;
            bIdx = 0;
        }
    }

    template <typename CopyT>
    __aicore__ inline void CopyVectorIn(LocalTensor<CopyT> &dst, GlobalTensor<CopyT> &src, uint64_t offset,
                                        uint64_t count)
    {
        const uint64_t rowBytes = count * static_cast<uint64_t>(sizeof(CopyT));
        if (rowBytes >= 32 && (rowBytes % 32) == 0) {
            DataCopy(dst, src[offset], static_cast<uint32_t>(count));
            return;
        }
        DataCopyParams params{1, static_cast<uint16_t>(rowBytes), 0, 0};
        DataCopyPadParams padParams{false, 0, 0, 0};
        DataCopyPad(dst, src[offset], params, padParams);
    }

    template <typename CopyT>
    __aicore__ inline void CopyVectorOut(GlobalTensor<CopyT> &dst, uint64_t offset, LocalTensor<CopyT> &src,
                                         uint64_t count)
    {
        const uint64_t rowBytes = count * static_cast<uint64_t>(sizeof(CopyT));
        if (rowBytes >= 32 && (rowBytes % 32) == 0) {
            DataCopy(dst[offset], src, static_cast<uint32_t>(count));
            return;
        }
        DataCopyParams params{1, static_cast<uint16_t>(rowBytes), 0, 0};
        DataCopyPad(dst[offset], src, params);
    }

    GlobalTensor<T> q_, k_, g_, beta_, aqk_, scoreWs_;
    GlobalTensor<float> akkd_, cmatWs_;
    GlobalTensor<int64_t> cuSeqlens_, chunkIndices_;

    uint64_t batch_ = 0, t_ = 0, h_ = 0, hv_ = 0, kDim_ = 0, bt_ = 0, bc_ = 0, nc_ = 0, totalTasks_ = 0,
             usedCoreNum_ = 0, depth_ = 2, coreIdx_ = 0, group_ = 1;
    bool hasVarlen_ = false;
    float scale_ = 1.0f;
};

} // namespace kda_isub

#endif // CHUNK_KDA_FWD_INTRA_SUB_CHUNK_COMMON_H
