#!/usr/bin/env python3
"""Generate a typed C++ thin adapter from an op ABI spec (Phase 0 codegen).

Supported kinds (v0): tensor, optional_tensor, out_tensor, int_array, int64,
bool, double, float. Other kinds raise so the tool stays honest about what it
can generate.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


_CPP_SCALAR = {
    "int64": "int64_t",
    "bool": "bool",
    "double": "double",
    "float": "float",
}


def _aclnn_typename(kind: str) -> str:
    if kind in ("tensor", "optional_tensor", "out_tensor"):
        return "const aclTensor*"
    if kind == "int_array":
        return "const aclIntArray*"
    if kind == "char_ptr":
        return "const char*"
    return _CPP_SCALAR[kind]


def _python_param(kind: str, name: str) -> str:
    if kind in ("tensor", "out_tensor"):
        return f"const at::Tensor& {name}"
    if kind == "optional_tensor":
        return f"const c10::optional<at::Tensor>& {name}"
    if kind == "int_array":
        return f"const std::vector<int64_t>& {name}"
    if kind == "char_ptr":
        return f"const std::string& {name}"
    return f"{_CPP_SCALAR[kind]} {name}"


def _arg_token(kind: str, name: str, index: int) -> str:
    if kind in ("tensor", "optional_tensor", "out_tensor"):
        return f"views[{index}]->get()"
    if kind == "int_array":
        return f"{name}.get()"
    if kind == "char_ptr":
        return f"{name}.c_str()"
    return name


def generate(spec: dict) -> str:
    args = spec["args"]
    out_kinds = [a for a in args if a["kind"] == "out_tensor"]
    if len(out_kinds) != 1:
        raise ValueError("codegen v0 requires exactly one out_tensor arg")
    op = spec["aclnn_name"]
    fn = spec["python_name"]
    params = [_python_param(a["kind"], a["name"]) for a in args
              if a["kind"] != "out_tensor"]
    params.append("uint64_t stream")
    scalar_params = [
        (a["name"], _CPP_SCALAR[a["kind"]])
        for a in args if a["kind"] in _CPP_SCALAR
    ]
    anchor = next(
        a["name"] for a in args
        if a["kind"] in ("tensor", "optional_tensor"))

    lines = []
    lines.append("// Generated by op_spec_codegen.py — do not edit by hand.")
    lines.append(f"// spec: {spec['aclnn_name']}")
    lines.append("#include <ATen/ATen.h>")
    lines.append("#include <torch/extension.h>")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <memory>")
    lines.append("#include <string>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append('#include "thin_launcher/runtime.h"')
    lines.append('#include "thin_launcher/tensor_desc.h"')
    lines.append("")
    lines.append("namespace fla_npu_thin {")
    lines.append("namespace {")
    lines.append("typedef struct aclOpExecutor aclOpExecutor;")
    lines.append("")
    cpp_types = [_aclnn_typename(a["kind"]) for a in args]
    lines.append(f"using {fn}_GetWorkspaceFn = int (*)(")
    lines.append("    " + ",\n    ".join(cpp_types) + ",")
    lines.append("    uint64_t*, aclOpExecutor**);")
    lines.append("using LaunchFn = int (*)(void*, uint64_t, aclOpExecutor*, void*);")
    lines.append("}  // namespace")
    lines.append("")
    lines.append(f"at::Tensor {fn}(")
    lines.append("    " + ",\n    ".join(params) + ") {")
    lines.extend(_output_alloc_lines(spec))
    lines.append("")
    lines.append("  std::vector<std::unique_ptr<AclTensorView>> views;")
    lines.append("  views.reserve(8);")
    for i, a in enumerate(args):
        kind = a["kind"]
        name = a["name"]
        if kind == "tensor":
            lines.append(f"  views.push_back(std::make_unique<AclTensorView>({name}));")
        elif kind == "out_tensor":
            lines.append(f"  views.push_back(std::make_unique<AclTensorView>(output));")
        elif kind == "optional_tensor":
            lines.append(
                f"  views.push_back(std::make_unique<AclTensorView>("
                f"{name}.has_value() && {name}->defined() ? *{name} : at::Tensor()));")
    int_array_names = [a["name"] for a in args if a["kind"] == "int_array"]
    for name in int_array_names:
        lines.append(f"  AclIntArrayView {name}_view({name});")
    lines.append("")
    lines.append("  auto& rt = Runtime::instance();")
    lines.append(
        f"  auto get_ws = reinterpret_cast<{fn}_GetWorkspaceFn>("
        f"rt.symbol(\"{op}GetWorkspaceSize\"));")
    lines.append(f"  auto launch = reinterpret_cast<LaunchFn>(rt.symbol(\"{op}\"));")
    lines.append("")
    lines.append("  uint64_t workspace_size = 0;")
    lines.append("  aclOpExecutor* executor = nullptr;")
    tokens = []
    view_i = 0
    for a in args:
        kind = a["kind"]
        if kind in ("tensor", "optional_tensor", "out_tensor"):
            tokens.append(f"views[{view_i}]->get()")
            view_i += 1
        elif kind == "int_array":
            tokens.append(f"{a['name']}_view.get()")
        elif kind == "char_ptr":
            tokens.append(f"{a['name']}.c_str()")
        else:
            tokens.append(a["name"])
    lines.append("  const int get_ret = get_ws(")
    lines.append("      " + ",\n      ".join(tokens) + ",")
    lines.append("      &workspace_size, &executor);")
    lines.append(f'  TORCH_CHECK(get_ret == 0, "{op}GetWorkspaceSize failed: ", get_ret);')
    lines.append("")
    lines.append("  void* workspace_ptr = nullptr;")
    lines.append("  at::Tensor workspace;")
    lines.append("  if (workspace_size != 0) {")
    lines.append("    workspace = at::empty({static_cast<int64_t>(workspace_size)},")
    lines.append(
        f"                          at::TensorOptions().dtype(at::kByte).device({anchor}.device()));")
    lines.append("    workspace_ptr = workspace.data_ptr();")
    lines.append("  }")
    lines.append("  const int launch_ret =")
    lines.append("      launch(workspace_ptr, workspace_size, executor,")
    lines.append("             reinterpret_cast<void*>(stream));")
    lines.append(f'  TORCH_CHECK(launch_ret == 0, "{op} failed: ", launch_ret);')
    lines.append("  return output;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace fla_npu_thin")
    lines.append("")
    return "\n".join(lines)


def _output_alloc_lines(spec: dict) -> list[str]:
    output = spec.get("output", {})
    source = output.get("source", spec["args"][0]["name"])
    dtype = output.get("dtype", "float32")
    shape = output.get("shape")
    if dtype == "same":
        if shape:
            raise ValueError("output_dtype 'same' with explicit shape is unsupported")
        return [f"  auto output = at::empty_like({source});"]
    if shape is not None:
        parts = []
        for item in shape:
            if "dim" in item:
                parts.append(f"{item['arg']}.size({item['dim']})")
            elif "arg" in item:
                parts.append(item["arg"])
            else:
                raise ValueError(f"bad output shape item: {item!r}")
        sizes = ", ".join(parts)
        if dtype == "output_dtype":
            return [
                f"  auto output = (output_dtype == \"float32\")",
                f"      ? at::empty({{{sizes}}}, {source}.options().dtype(at::kFloat))",
                f"      : at::empty({{{sizes}}}, {source}.options().dtype(at::kBFloat16));",
            ]
        aten = {"float32": "at::kFloat", "bfloat16": "at::kBFloat16"}.get(dtype)
        if aten is None:
            raise ValueError(f"unsupported output dtype: {dtype}")
        return [
            f"  auto output = at::empty({{{sizes}}}, "
            f"{source}.options().dtype({aten}));"
        ]
    if dtype == "output_dtype":
        return [
            f"  auto output = (output_dtype == \"float32\")",
            f"      ? at::empty({source}.sizes(), {source}.options().dtype(at::kFloat))",
            f"      : at::empty({source}.sizes(), {source}.options().dtype(at::kBFloat16));",
        ]
    aten = {"float32": "at::kFloat", "bfloat16": "at::kBFloat16"}.get(dtype)
    if aten is None:
        raise ValueError(f"unsupported output dtype: {dtype}")
    return [
        f"  auto output = at::empty({source}.sizes(), "
        f"{source}.options().dtype({aten}));"
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    args.output.write_text(generate(spec), encoding="utf-8")
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
