"""Generated by tools/op_stable_codegen.py -- do not edit by hand."""
from ._stable import (  # noqa: F401
    _call,
    _char_code,
    _current_stream_ptr,
    _host_ints,
    _op,
)

_GENERATED_HASH = "02952a2309f4f9d96f2a016f0e5612d7"

_SIG = {
    "npu_causal_conv1d_bwd": [("x", "tensor"), ("y", "optional_tensor"), ("weight", "tensor"), ("dy", "tensor"), ("initial_state", "optional_tensor"), ("dht", "optional_tensor"), ("query_start_loc", "int_array"), ("activation", "int64"), ("input_layout", "char_ptr")],
    "npu_chunk_bwd_dqkwg": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("h", "tensor"), ("dox", "tensor"), ("dh", "tensor"), ("dv", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("w", "optional_tensor"), ("g_gamma", "optional_tensor"), ("scale", "float"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("transpose_state_layout", "bool")],
    "npu_chunk_bwd_dv_local": [("q", "tensor"), ("k", "tensor"), ("d_o", "tensor"), ("g", "tensor"), ("g_gamma", "optional_tensor"), ("A", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64")],
    "npu_chunk_fwd_h": [("k", "tensor"), ("w", "tensor"), ("u", "tensor"), ("g", "optional_tensor"), ("gk", "optional_tensor"), ("initial_state", "optional_tensor"), ("output_final_state", "bool"), ("chunk_size", "int64"), ("save_new_value", "bool"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("use_exp2", "bool"), ("state_v_first", "bool")],
    "npu_chunk_fwd_o": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("h", "tensor"), ("g", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("transpose_state_layout", "bool"), ("output_layout", "char_ptr")],
    "npu_chunk_gated_delta_rule_bwd_dhu": [("q", "tensor"), ("k", "tensor"), ("w", "tensor"), ("d_o", "tensor"), ("dv", "tensor"), ("g", "optional_tensor"), ("gK", "optional_tensor"), ("h0", "optional_tensor"), ("dht", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("transpose_state_layout", "bool")],
    "npu_chunk_gated_delta_rule_bwd_finalize": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("v_new", "tensor"), ("do", "tensor"), ("du", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("h", "tensor"), ("dh", "tensor"), ("a", "tensor"), ("q_rstd", "optional_tensor"), ("k_rstd", "optional_tensor"), ("beta_raw", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("use_qk_l2_norm_in_kernel", "bool"), ("use_beta_sigmoid_in_kernel", "bool"), ("use_gate_in_kernel", "bool"), ("state_v_first", "bool"), ("use_exp2", "bool")],
    "npu_chunk_gated_delta_rule_fwd": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("a_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("initial_state", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("layout", "char_ptr"), ("scale", "double"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("use_qk_l2norm_in_kernel", "bool"), ("allow_neg_eigval", "bool"), ("state_v_first", "bool"), ("output_final_state", "bool"), ("disable_recompute", "bool"), ("return_intermediate_states", "bool"), ("use_gate_in_kernel", "bool"), ("use_beta_sigmoid_in_kernel", "bool")],
    "npu_chunk_gated_delta_rule_fwd_h": [("k", "tensor"), ("w", "tensor"), ("u", "tensor"), ("g", "optional_tensor"), ("gk", "optional_tensor"), ("initial_state", "optional_tensor"), ("output_final_state", "bool"), ("chunk_size", "int64"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("state_v_first", "bool")],
    "npu_chunk_gated_delta_rule_fwd_prepare": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("a_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64"), ("allow_neg_eigval", "bool"), ("use_exp2", "bool"), ("output_a", "bool"), ("use_beta_sigmoid_in_kernel", "bool"), ("use_gate_in_kernel", "bool")],
    "npu_chunk_gdn_bwd_intra": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("d_o", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("use_exp2", "bool")],
    "npu_chunk_kda_bwd": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("gk", "tensor"), ("Aqk", "tensor"), ("Akk", "tensor"), ("w", "optional_tensor"), ("qg", "optional_tensor"), ("kg", "optional_tensor"), ("v_new", "optional_tensor"), ("h", "optional_tensor"), ("d_o", "tensor"), ("raw_g", "optional_tensor"), ("A_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("initial_state", "optional_tensor"), ("dht", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("safe_gate", "bool"), ("use_gate_in_kernel", "bool"), ("lower_bound", "double"), ("disable_recompute", "bool"), ("use_exp2", "bool"), ("state_v_first", "bool")],
    "npu_chunk_kda_bwd_intra": [("q", "tensor"), ("k", "tensor"), ("gk", "tensor"), ("beta", "tensor"), ("dAqk", "tensor"), ("dAkk", "tensor"), ("dq", "tensor"), ("dk", "tensor"), ("db", "tensor"), ("dg", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64"), ("safe_gate", "bool"), ("layout", "char_ptr")],
    "npu_chunk_kda_bwd_recompute": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("a", "tensor"), ("A_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("lower_bound", "double"), ("use_gate_in_kernel", "bool")],
    "npu_chunk_kda_fwd": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("A_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("initial_state", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("layout", "char_ptr"), ("scale", "double"), ("chunk_size", "int64"), ("safe_gate", "bool"), ("lower_bound", "double"), ("use_gate_in_kernel", "bool"), ("state_v_first", "bool"), ("output_final_state", "bool"), ("disable_recompute", "bool"), ("return_intermediate_states", "bool")],
    "npu_chunk_local_cumsum": [("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices_out", "int_array"), ("chunk_size", "int64"), ("reverse", "bool"), ("scale", "double"), ("head_first", "bool"), ("output_dtype", "char_ptr")],
    "npu_chunk_scaled_dot_kkt": [("k", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_fast_gelu_custom": [("self", "tensor")],
    "npu_fast_gelu_custom_backward": [("grad", "tensor"), ("self", "tensor")],
    "npu_kda_gate_cumsum": [("g", "tensor"), ("A_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_size", "int64"), ("use_gate_in_kernel", "bool"), ("safe_gate", "bool"), ("lower_bound", "double")],
    "npu_prepare_wy_repr_bwd": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_prepare_wy_repr_bwd_da": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_prepare_wy_repr_bwd_full": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dA", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_recompute_w_u_fwd": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("g", "optional_tensor"), ("gk", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_solve_tri": [("x", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("layout", "char_ptr")],
    "_causal_conv1d_launch": [("x", "tensor"), ("weight", "tensor"), ("bias", "optional_tensor"), ("conv_states", "optional_tensor"), ("query_start_loc", "optional_tensor"), ("cache_indices", "optional_tensor"), ("has_initial_state", "optional_tensor"), ("num_accepted_tokens", "optional_tensor"), ("query_start_loc_cpu", "int_array"), ("cache_indices_cpu", "int_array"), ("has_initial_state_cpu", "int_array"), ("num_accepted_tokens_cpu", "int_array"), ("activation", "char_ptr"), ("pad_slot_id", "int64"), ("null_block_id", "int64"), ("run_mode", "int64"), ("head_num", "int64"), ("max_query_len", "int64")],
}

_ENUM = {
    "npu_causal_conv1d_bwd": {"input_layout": {'BSND': 0, 'BNSD': 1, 'NTD': 2, 'TND': 3}},
    "npu_chunk_fwd_o": {"output_layout": {'BNSD': 0, 'BSND': 1, 'TND': 2, 'NTD': 3}},
    "npu_chunk_gated_delta_rule_fwd": {"layout": {'BSND': 0, 'BNSD': 1, 'NTD': 2, 'TND': 3}},
    "npu_chunk_kda_bwd_intra": {"layout": {'BSND': 0, 'BNSD': 1}},
    "npu_chunk_kda_fwd": {"layout": {'BSND': 0, 'BNSD': 1, 'TND': 2, 'NTD': 3}},
    "npu_chunk_local_cumsum": {"output_dtype": {'float32': 0, 'bfloat16': 1}},
    "npu_solve_tri": {"layout": {'bsnd': 0, 'bnsd': 1, 'tnd': 2, 'ntd': 3}},
    "_causal_conv1d_launch": {"activation": {'none': 0, 'silu': 1, 'swish': 2}},
}

_RET = {
    "npu_causal_conv1d_bwd": [(0, None), (1, None), (2, None), (3, None)],
    "npu_chunk_bwd_dqkwg": [(0, None), (1, None), (2, None), (3, None)],
    "npu_chunk_bwd_dv_local": [(0, None)],
    "npu_chunk_fwd_h": [(0, None), (1, None), (2, 'output_final_state')],
    "npu_chunk_fwd_o": [(0, None)],
    "npu_chunk_gated_delta_rule_bwd_dhu": [(0, None), (1, 'h0.has_value() && h0->defined()'), (2, None)],
    "npu_chunk_gated_delta_rule_bwd_finalize": [(0, None), (1, None), (2, None), (3, None), (4, None)],
    "npu_chunk_gated_delta_rule_fwd": [(0, None), (1, 'output_final_state'), (2, None), (3, None), (4, None), (5, None), (6, None), (7, '!disable_recompute'), (8, '!disable_recompute'), (9, 'return_intermediate_states')],
    "npu_chunk_gated_delta_rule_fwd_h": [(0, None), (1, None), (2, 'output_final_state')],
    "npu_chunk_gated_delta_rule_fwd_prepare": [(0, None), (1, None), (2, None), (3, None), (4, None), (5, None), (6, None), (7, None), (8, 'use_beta_sigmoid_in_kernel')],
    "npu_chunk_gdn_bwd_intra": [(0, None), (1, None), (2, None)],
    "npu_chunk_kda_bwd": [(0, None), (1, None), (2, None), (3, None), (4, None), (5, None), (6, None), (7, None)],
    "npu_chunk_kda_bwd_intra": [(0, None), (1, None), (2, None), (3, None)],
    "npu_chunk_kda_bwd_recompute": [(0, None), (1, None), (2, None), (3, None), (4, 'use_gate_in_kernel')],
    "npu_chunk_kda_fwd": [(0, None), (1, 'output_final_state'), (2, '!use_gate_in_kernel || disable_recompute'), (3, None), (4, None), (5, 'disable_recompute'), (6, 'disable_recompute'), (7, 'disable_recompute'), (8, 'disable_recompute'), (9, 'disable_recompute'), (10, 'disable_recompute || return_intermediate_states')],
    "npu_chunk_local_cumsum": [(0, None)],
    "npu_chunk_scaled_dot_kkt": [(0, None)],
    "npu_fast_gelu_custom": [(0, None)],
    "npu_fast_gelu_custom_backward": [(0, None)],
    "npu_kda_gate_cumsum": [(0, None)],
    "npu_prepare_wy_repr_bwd": [(0, None), (1, None), (2, None), (3, None)],
    "npu_prepare_wy_repr_bwd_da": [(0, None)],
    "npu_prepare_wy_repr_bwd_full": [(0, None), (1, None), (2, None), (3, None)],
    "npu_recompute_w_u_fwd": [(0, None), (1, None)],
    "npu_solve_tri": [(0, None)],
    "_causal_conv1d_launch": [(0, None)],
}

def npu_causal_conv1d_bwd(x, y, weight, dy, initial_state=None, dht=None, *, query_start_loc=None, activation=0, input_layout="BSND"):
    return _op("npu_causal_conv1d_bwd")(
        x,
        y,
        weight,
        dy,
        initial_state,
        dht,
        _host_ints(query_start_loc),
        activation,
        _char_code("npu_causal_conv1d_bwd", "input_layout", input_layout),
        _current_stream_ptr(),
    )

def npu_chunk_bwd_dqkwg(q, k, v, g, h, dox, dh, dv, chunk_size, *, cu_seqlens=None, chunk_indices=None, w=None, g_gamma=None, scale=None, use_exp2=None, transpose_state_layout=None):
    return _op("npu_chunk_bwd_dqkwg")(
        q,
        k,
        v,
        g,
        h,
        dox,
        dh,
        dv,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        w,
        g_gamma,
        scale,
        chunk_size,
        use_exp2,
        transpose_state_layout,
        _current_stream_ptr(),
    )

def npu_chunk_bwd_dv_local(q, k, d_o, g, scale, chunk_size, *, g_gamma=None, A=None, cu_seqlens=None, chunk_indices=None):
    return _op("npu_chunk_bwd_dv_local")(
        q,
        k,
        d_o,
        g,
        g_gamma,
        A,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        _current_stream_ptr(),
    )

def npu_chunk_fwd_h(k, w, u, *, g=None, gk=None, initial_state=None, output_final_state=False, chunk_size=64, save_new_value=True, cu_seqlens=None, chunk_indices=None, use_exp2=False, state_v_first=False):
    if cu_seqlens and not chunk_indices:
        chunk_indices = []
        for _seq in range(len(cu_seqlens) - 1):
            _len = cu_seqlens[_seq + 1] - cu_seqlens[_seq]
            for _c in range((_len + chunk_size - 1) // chunk_size):
                chunk_indices.extend((_seq, _c))
    return _op("npu_chunk_fwd_h")(
        k,
        w,
        u,
        g,
        gk,
        initial_state,
        output_final_state,
        chunk_size,
        save_new_value,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        use_exp2,
        state_v_first,
        _current_stream_ptr(),
    )

def npu_chunk_fwd_o(q, k, v, h, scale, *, g=None, cu_seqlens=None, chunk_indices=None, chunk_size=None, use_exp2=False, transpose_state_layout=False, output_layout="BNSD", g_gamma=None):
    return _op("npu_chunk_fwd_o")(
        q,
        k,
        v,
        h,
        g,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        use_exp2,
        transpose_state_layout,
        _char_code("npu_chunk_fwd_o", "output_layout", output_layout),
        _current_stream_ptr(),
    )

def npu_chunk_gated_delta_rule_bwd_dhu(q, k, w, d_o, dv, scale, chunk_size, *, g=None, gK=None, h0=None, dht=None, cu_seqlens=None, chunk_indices=None, use_exp2=False, transpose_state_layout=False):
    return _op("npu_chunk_gated_delta_rule_bwd_dhu")(
        q,
        k,
        w,
        d_o,
        dv,
        g,
        gK,
        h0,
        dht,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        use_exp2,
        transpose_state_layout,
        _current_stream_ptr(),
    )

def npu_chunk_gated_delta_rule_bwd_finalize(q, k, v, v_new, do, du, g, beta, h, dh, a, *, q_rstd=None, k_rstd=None, beta_raw=None, cu_seqlens=None, chunk_indices=None, scale=None, chunk_size=64, use_qk_l2_norm_in_kernel=False, use_beta_sigmoid_in_kernel=False, use_gate_in_kernel=False, state_v_first=False, use_exp2=True):
    scale = (128.0 ** -0.5) if scale is None else float(scale)
    if int(chunk_size) != 64 or bool(use_gate_in_kernel) or not bool(use_exp2):
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_chunk_gated_delta_rule_bwd_finalize(q, k, v, v_new, do, du, g, beta, h, dh, a, q_rstd=q_rstd, k_rstd=k_rstd, beta_raw=beta_raw, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, scale=scale, chunk_size=chunk_size, use_qk_l2_norm_in_kernel=use_qk_l2_norm_in_kernel, use_beta_sigmoid_in_kernel=use_beta_sigmoid_in_kernel, use_gate_in_kernel=use_gate_in_kernel, state_v_first=state_v_first, use_exp2=use_exp2)
    return _op("npu_chunk_gated_delta_rule_bwd_finalize")(
        q,
        k,
        v,
        v_new,
        do,
        du,
        g,
        beta,
        h,
        dh,
        a,
        q_rstd,
        k_rstd,
        beta_raw,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        use_qk_l2_norm_in_kernel,
        use_beta_sigmoid_in_kernel,
        use_gate_in_kernel,
        state_v_first,
        use_exp2,
        _current_stream_ptr(),
    )

def npu_chunk_gated_delta_rule_fwd(q, k, v, g, beta, *, initial_state=None, cu_seqlens=None, chunk_indices=None, layout="BNSD", scale=None, chunk_size=64, use_exp2=False, use_qk_l2norm_in_kernel=False, allow_neg_eigval=False, state_v_first=False, output_final_state=False, disable_recompute=False, return_intermediate_states=False, use_gate_in_kernel=False, use_beta_sigmoid_in_kernel=False):
    layout = str(layout)
    if scale is None:
        scale = float(q.shape[3]) ** -0.5
    if cu_seqlens is not None and chunk_indices is None:
        chunk_indices = []
        for _seq in range(len(cu_seqlens) - 1):
            _len = cu_seqlens[_seq + 1] - cu_seqlens[_seq]
            for _c in range((_len + int(chunk_size) - 1) // int(chunk_size)):
                chunk_indices.extend((_seq, _c))
    a_log = None
    dt_bias = None
    result = _op("npu_chunk_gated_delta_rule_fwd")(
        q,
        k,
        v,
        g,
        beta,
        None,
        None,
        initial_state,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        _char_code("npu_chunk_gated_delta_rule_fwd", "layout", layout),
        scale,
        chunk_size,
        use_exp2,
        use_qk_l2norm_in_kernel,
        allow_neg_eigval,
        state_v_first,
        output_final_state,
        disable_recompute,
        return_intermediate_states,
        use_gate_in_kernel,
        use_beta_sigmoid_in_kernel,
        _current_stream_ptr(),
    )
    out = [result[0]]
    if output_final_state:
        out.append(result[1])
    else:
        out.append(None)
    if not disable_recompute:
        out.append(result[7])
        out.append(result[8])
    if return_intermediate_states:
        out.append(result[9])
    return tuple(out)

def npu_chunk_gated_delta_rule_fwd_h(k, w, u, g=None, *, gk=None, initial_state=None, output_final_state=False, chunk_size=None, cu_seqlens=None, chunk_indices=None, state_v_first=False):
    if cu_seqlens and not chunk_indices:
        chunk_indices = []
        for _seq in range(len(cu_seqlens) - 1):
            _len = cu_seqlens[_seq + 1] - cu_seqlens[_seq]
            for _c in range((_len + chunk_size - 1) // chunk_size):
                chunk_indices.extend((_seq, _c))
    return _op("npu_chunk_gated_delta_rule_fwd_h")(
        k,
        w,
        u,
        g,
        gk,
        initial_state,
        output_final_state,
        chunk_size,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        state_v_first,
        _current_stream_ptr(),
    )

def npu_chunk_gated_delta_rule_fwd_prepare(q, k, v, g, beta, chunk_size=64, *, a_log=None, dt_bias=None, cu_seqlens=None, chunk_indices=None, allow_neg_eigval=False, use_exp2=False, output_a=True, use_beta_sigmoid_in_kernel=False, use_gate_in_kernel=False, use_qk_l2norm_in_kernel=False):
    import torch
    if not (bool(use_qk_l2norm_in_kernel) and bool(use_exp2) and int(chunk_size) == 64):
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_chunk_gated_delta_rule_fwd_prepare(q, k, v, g, beta, chunk_size, use_qk_l2norm_in_kernel=use_qk_l2norm_in_kernel, use_gate_in_kernel=use_gate_in_kernel, use_beta_sigmoid_in_kernel=use_beta_sigmoid_in_kernel, allow_neg_eigval=allow_neg_eigval, use_exp2=use_exp2, a_log=a_log, dt_bias=dt_bias, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, output_a=output_a)
    if use_gate_in_kernel:
        # aclnn rejects a non-null aLogOptional ("use_gate_in_kernel currently only
        # supports false"), and the ctypes reference raises ValueError for the same
        # request: keep that error surface on the reference path.
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_chunk_gated_delta_rule_fwd_prepare(q, k, v, g, beta, chunk_size, use_qk_l2norm_in_kernel=use_qk_l2norm_in_kernel, use_gate_in_kernel=use_gate_in_kernel, use_beta_sigmoid_in_kernel=use_beta_sigmoid_in_kernel, allow_neg_eigval=allow_neg_eigval, use_exp2=use_exp2, a_log=a_log, dt_bias=dt_bias, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, output_a=output_a)
    result = _op("npu_chunk_gated_delta_rule_fwd_prepare")(
        q,
        k,
        v,
        g,
        beta,
        a_log,
        dt_bias,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        allow_neg_eigval,
        use_exp2,
        output_a,
        use_beta_sigmoid_in_kernel,
        use_gate_in_kernel,
        _current_stream_ptr(),
    )
    if result[8] is None:
        return (result[4], result[5], result[6], result[7], beta.to(dtype=torch.float32), result[0], result[1], result[2], result[3])
    return (result[4], result[5], result[6], result[7], result[8], result[0], result[1], result[2], result[3])

def npu_chunk_gdn_bwd_intra(q, k, v, g, beta, A, d_o, scale, chunk_size, *, cu_seqlens=None, chunk_indices=None, use_exp2=True):
    return _op("npu_chunk_gdn_bwd_intra")(
        q,
        k,
        v,
        g,
        beta,
        A,
        d_o,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        use_exp2,
        _current_stream_ptr(),
    )

def npu_chunk_kda_bwd(q, k, v, beta, gk, Aqk, Akk, w, qg, kg, v_new, h, d_o, scale, *, raw_g=None, A_log=None, dt_bias=None, initial_state=None, dht=None, cu_seqlens=None, chunk_indices=None, chunk_size=64, safe_gate=True, use_gate_in_kernel=False, lower_bound=-5.0, disable_recompute=True, use_exp2=True, state_v_first=False):
    if not (cu_seqlens is None and chunk_indices is None and int(chunk_size) == 64 and bool(safe_gate) and not bool(use_gate_in_kernel) and bool(disable_recompute) and bool(use_exp2) and not bool(state_v_first) and raw_g is None and A_log is None and dt_bias is None and initial_state is None and dht is None and q.dim() == 4 and q.shape[1] % 2 == 0 and q.shape[2] % 64 == 0 and all(x is not None for x in (w, qg, kg, v_new, h))):
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_chunk_kda_bwd(q, k, v, beta, gk, Aqk, Akk, w, qg, kg, v_new, h, d_o, scale, raw_g=raw_g, A_log=A_log, dt_bias=dt_bias, initial_state=initial_state, dht=dht, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, chunk_size=chunk_size, safe_gate=safe_gate, lower_bound=lower_bound, use_gate_in_kernel=use_gate_in_kernel, disable_recompute=disable_recompute, use_exp2=use_exp2, state_v_first=state_v_first)
    return _op("npu_chunk_kda_bwd")(
        q,
        k,
        v,
        beta,
        gk,
        Aqk,
        Akk,
        w,
        qg,
        kg,
        v_new,
        h,
        d_o,
        raw_g,
        A_log,
        dt_bias,
        initial_state,
        dht,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        scale,
        chunk_size,
        safe_gate,
        use_gate_in_kernel,
        lower_bound,
        disable_recompute,
        use_exp2,
        state_v_first,
        _current_stream_ptr(),
    )

def npu_chunk_kda_bwd_intra(q, k, gk, beta, dAqk, dAkk, dq, dk, db, dg, *, cu_seqlens=None, chunk_indices=None, chunk_size=64, safe_gate=True, layout="BSND"):
    layout = str(layout)
    if not (layout == "BNSD" and cu_seqlens is None and chunk_indices is None and int(chunk_size) == 64 and bool(safe_gate)):
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_chunk_kda_bwd_intra(q, k, gk, beta, dAqk, dAkk, dq, dk, db, dg, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, chunk_size=chunk_size, safe_gate=safe_gate, layout=layout)
    return _op("npu_chunk_kda_bwd_intra")(
        q,
        k,
        gk,
        beta,
        dAqk,
        dAkk,
        dq,
        dk,
        db,
        dg,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        safe_gate,
        _char_code("npu_chunk_kda_bwd_intra", "layout", layout),
        _current_stream_ptr(),
    )

def npu_chunk_kda_bwd_recompute(q, k, v, g, beta, a, chunk_size, *, A_log=None, dt_bias=None, cu_seqlens=None, chunk_indices=None, use_exp2=True, lower_bound=-5.0, use_gate_in_kernel=True):
    result = _op("npu_chunk_kda_bwd_recompute")(
        q,
        k,
        v,
        g,
        beta,
        a,
        A_log,
        dt_bias,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        use_exp2,
        lower_bound,
        use_gate_in_kernel,
        _current_stream_ptr(),
    )
    return (result[4], result[0], result[1], result[2], result[3])

def npu_chunk_kda_fwd(q, k, v, g, beta, scale, chunk_size=64, *, A_log=None, dt_bias=None, initial_state=None, cu_seqlens=None, chunk_indices=None, layout="BSND", safe_gate=False, lower_bound=None, use_gate_in_kernel=False, state_v_first=False, output_final_state=False, disable_recompute=False, return_intermediate_states=False):
    layout = str(layout)
    safe_gate = bool(safe_gate)
    use_gate_in_kernel = bool(use_gate_in_kernel)
    state_v_first = bool(state_v_first)
    output_final_state = bool(output_final_state)
    disable_recompute = bool(disable_recompute)
    return_intermediate_states = bool(return_intermediate_states)
    if scale is None:
        scale = float(q.shape[2] if layout in ("TND", "NTD") else q.shape[3]) ** -0.5
    if lower_bound is None:
        lower_bound = -5.0
    if cu_seqlens and not chunk_indices:
        chunk_indices = []
        for _seq in range(len(cu_seqlens) - 1):
            _len = cu_seqlens[_seq + 1] - cu_seqlens[_seq]
            for _c in range((_len + chunk_size - 1) // chunk_size):
                chunk_indices.extend((_seq, _c))
    result = _op("npu_chunk_kda_fwd")(
        q,
        k,
        v,
        g,
        beta,
        A_log,
        dt_bias,
        initial_state,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        _char_code("npu_chunk_kda_fwd", "layout", layout),
        scale,
        chunk_size,
        safe_gate,
        lower_bound,
        use_gate_in_kernel,
        state_v_first,
        output_final_state,
        disable_recompute,
        return_intermediate_states,
        _current_stream_ptr(),
    )
    out = [result[0]]
    out.append(result[1] if output_final_state else None)
    out.append(result[2] if (not use_gate_in_kernel or disable_recompute) else None)
    out.append(result[3])
    out.append(result[4])
    out.append(result[5] if disable_recompute else None)
    out.append(result[6] if disable_recompute else None)
    out.append(result[7] if disable_recompute else None)
    out.append(result[8] if disable_recompute else None)
    out.append(result[9] if disable_recompute else None)
    out.append(result[10] if (disable_recompute or return_intermediate_states) else None)
    out.append(initial_state)
    return tuple(out)

def npu_chunk_local_cumsum(g, chunk_size, *, cu_seqlens=None, chunk_indices_out=None, reverse=False, scale=1.0, head_first=True, output_dtype="float32"):
    return _op("npu_chunk_local_cumsum")(
        g,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices_out),
        chunk_size,
        reverse,
        scale,
        head_first,
        _char_code("npu_chunk_local_cumsum", "output_dtype", output_dtype),
        _current_stream_ptr(),
    )

def npu_chunk_scaled_dot_kkt(k, g, beta, *, cu_seqlens=None, chunk_indices=None, chunk_size=64):
    return _op("npu_chunk_scaled_dot_kkt")(
        k,
        g,
        beta,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        _current_stream_ptr(),
    )

def npu_fast_gelu_custom(self):
    return _op("npu_fast_gelu_custom")(
        self,
        _current_stream_ptr(),
    )

def npu_fast_gelu_custom_backward(grad, self):
    return _op("npu_fast_gelu_custom_backward")(
        grad,
        self,
        _current_stream_ptr(),
    )

def npu_kda_gate_cumsum(g, chunk_size, *, A_log=None, dt_bias=None, cu_seqlens=None, use_gate_in_kernel=False, safe_gate=False, lower_bound=None):
    return _op("npu_kda_gate_cumsum")(
        g,
        A_log,
        dt_bias,
        _host_ints(cu_seqlens),
        chunk_size,
        use_gate_in_kernel,
        safe_gate,
        lower_bound,
        _current_stream_ptr(),
    )

def npu_prepare_wy_repr_bwd(k, v, beta, A, dw, du, g, chunk_size, *, cu_seqlens=None, chunk_indices=None):
    return _op("npu_prepare_wy_repr_bwd")(
        k,
        v,
        beta,
        A,
        dw,
        du,
        g,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        _current_stream_ptr(),
    )

def npu_prepare_wy_repr_bwd_da(k, v, beta, A, dw, du, g, *, cu_seqlens=None, chunk_indices=None, chunk_size):
    return _op("npu_prepare_wy_repr_bwd_da")(
        k,
        v,
        beta,
        A,
        dw,
        du,
        g,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        _current_stream_ptr(),
    )

def npu_prepare_wy_repr_bwd_full(k, v, beta, A, dA, dw, du, g, chunk_size, *, cu_seqlens=None, chunk_indices=None):
    return _op("npu_prepare_wy_repr_bwd_full")(
        k,
        v,
        beta,
        A,
        dA,
        dw,
        du,
        g,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        _current_stream_ptr(),
    )

def npu_recompute_w_u_fwd(k, v, beta, A, chunk_size, *, g=None, gk=None, cu_seqlens=None, chunk_indices=None):
    return _op("npu_recompute_w_u_fwd")(
        k,
        v,
        beta,
        A,
        g,
        gk,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        chunk_size,
        _current_stream_ptr(),
    )

def npu_solve_tri(x, *, cu_seqlens=None, chunk_indices=None, layout="bsnd"):
    layout = str(layout)
    # tnd kills the operator process on this OPP -- measured on both backends, with
    # and without cu_seqlens -- so refuse it instead of crashing. ntd is broken the
    # other way (ctypes returns all zeros for it) and stays on the ctypes path until
    # the kernel is fixed.
    if layout == "tnd":
        raise RuntimeError(
            "npu_solve_tri: layout='tnd' is refused because the operator crashes "
            "the process on this OPP (verified on both the ctypes and the "
            "Stable-ABI path). Use layout='bsnd'/'bnsd', or 'ntd' if the "
            "zero-filled result is acceptable.")
    if layout == "ntd":
        from fla_npu.ops.ascendc import _aclnn_ctypes as _ct
        return _ct.npu_solve_tri(x, cu_seqlens=cu_seqlens, chunk_indices=chunk_indices, layout=layout)
    return _op("npu_solve_tri")(
        x,
        _host_ints(cu_seqlens),
        _host_ints(chunk_indices),
        _char_code("npu_solve_tri", "layout", layout),
        _current_stream_ptr(),
    )

def _causal_conv1d_launch(*, x=None, weight=None, bias=None, conv_states=None, query_start_loc=None, cache_indices=None, has_initial_state=None, num_accepted_tokens=None, query_start_loc_cpu=None, cache_indices_cpu=None, has_initial_state_cpu=None, num_accepted_tokens_cpu=None, activation=None, pad_slot_id=None, null_block_id=None, run_mode=None, head_num=None, max_query_len=None):
    return _op("_causal_conv1d_launch")(
        x,
        weight,
        bias,
        conv_states,
        query_start_loc,
        cache_indices,
        has_initial_state,
        num_accepted_tokens,
        _host_ints(query_start_loc_cpu),
        _host_ints(cache_indices_cpu),
        _host_ints(has_initial_state_cpu),
        _host_ints(num_accepted_tokens_cpu),
        _char_code("_causal_conv1d_launch", "activation", activation),
        pad_slot_id,
        null_block_id,
        run_mode,
        head_num,
        max_query_len,
        _current_stream_ptr(),
    )

__all__ = [
    "npu_causal_conv1d_bwd",
    "npu_chunk_bwd_dqkwg",
    "npu_chunk_bwd_dv_local",
    "npu_chunk_fwd_h",
    "npu_chunk_fwd_o",
    "npu_chunk_gated_delta_rule_bwd_dhu",
    "npu_chunk_gated_delta_rule_bwd_finalize",
    "npu_chunk_gated_delta_rule_fwd",
    "npu_chunk_gated_delta_rule_fwd_h",
    "npu_chunk_gated_delta_rule_fwd_prepare",
    "npu_chunk_gdn_bwd_intra",
    "npu_chunk_kda_bwd",
    "npu_chunk_kda_bwd_intra",
    "npu_chunk_kda_bwd_recompute",
    "npu_chunk_kda_fwd",
    "npu_chunk_local_cumsum",
    "npu_chunk_scaled_dot_kkt",
    "npu_fast_gelu_custom",
    "npu_fast_gelu_custom_backward",
    "npu_kda_gate_cumsum",
    "npu_prepare_wy_repr_bwd",
    "npu_prepare_wy_repr_bwd_da",
    "npu_prepare_wy_repr_bwd_full",
    "npu_recompute_w_u_fwd",
    "npu_solve_tri",
    "_causal_conv1d_launch",
]
