"""Generated by tools/op_stable_codegen.py -- do not edit by hand."""
from ._stable import _call  # noqa: F401

_SIG = {
    "npu_chunk_bwd_dqkwg": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("g", "tensor"), ("h", "tensor"), ("dox", "tensor"), ("dh", "tensor"), ("dv", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("w", "optional_tensor"), ("g_gamma", "optional_tensor"), ("scale", "float"), ("chunk_size", "int64"), ("use_exp2", "bool"), ("transpose_state_layout", "bool")],
    "npu_chunk_bwd_dv_local": [("q", "tensor"), ("k", "tensor"), ("d_o", "tensor"), ("g", "tensor"), ("g_gamma", "optional_tensor"), ("A", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64")],
    "npu_chunk_gated_delta_rule_bwd_finalize": [("q", "tensor"), ("k", "tensor"), ("v", "tensor"), ("v_new", "tensor"), ("do", "tensor"), ("du", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("h", "tensor"), ("dh", "tensor"), ("a", "tensor"), ("q_rstd", "optional_tensor"), ("k_rstd", "optional_tensor"), ("beta_raw", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("scale", "double"), ("chunk_size", "int64"), ("use_qk_l2_norm_in_kernel", "bool"), ("use_beta_sigmoid_in_kernel", "bool"), ("use_gate_in_kernel", "bool"), ("state_v_first", "bool"), ("use_exp2", "bool")],
    "npu_chunk_kda_bwd_intra": [("q", "tensor"), ("k", "tensor"), ("gk", "tensor"), ("beta", "tensor"), ("dAqk", "tensor"), ("dAkk", "tensor"), ("dq", "tensor"), ("dk", "tensor"), ("db", "tensor"), ("dg", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64"), ("safe_gate", "bool"), ("layout", "char_ptr")],
    "npu_chunk_local_cumsum": [("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64"), ("reverse", "bool"), ("scale", "double"), ("head_first", "bool"), ("output_dtype", "char_ptr")],
    "npu_chunk_scaled_dot_kkt": [("k", "tensor"), ("g", "tensor"), ("beta", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_fast_gelu_custom": [("self", "tensor")],
    "npu_fast_gelu_custom_backward": [("grad", "tensor"), ("self", "tensor")],
    "npu_kda_gate_cumsum": [("g", "tensor"), ("A_log", "optional_tensor"), ("dt_bias", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_size", "int64"), ("use_gate_in_kernel", "bool"), ("safe_gate", "bool"), ("lower_bound", "double")],
    "npu_prepare_wy_repr_bwd": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_prepare_wy_repr_bwd_da": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_prepare_wy_repr_bwd_full": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("dA", "tensor"), ("dw", "tensor"), ("du", "tensor"), ("g", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_recompute_w_u_fwd": [("k", "tensor"), ("v", "tensor"), ("beta", "tensor"), ("A", "tensor"), ("g", "optional_tensor"), ("gk", "optional_tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("chunk_size", "int64")],
    "npu_solve_tri": [("x", "tensor"), ("cu_seqlens", "int_array"), ("chunk_indices", "int_array"), ("layout", "char_ptr")],
}

_ENUM = {
    "npu_chunk_kda_bwd_intra": {"layout": {'BSND': 0, 'BNSD': 1}},
    "npu_chunk_local_cumsum": {"output_dtype": {'float32': 0, 'bfloat16': 1}},
    "npu_solve_tri": {"layout": {'bsnd': 0, 'bnsd': 1, 'tnd': 2, 'ntd': 3}},
}

_RET = {
    "npu_chunk_bwd_dqkwg": [(0, None), (1, None), (2, None), (3, None)],
    "npu_chunk_bwd_dv_local": [(0, None)],
    "npu_chunk_gated_delta_rule_bwd_finalize": [(0, None), (1, None), (2, None), (3, None), (4, None)],
    "npu_chunk_kda_bwd_intra": [(0, None), (1, None), (2, None), (3, None)],
    "npu_chunk_local_cumsum": [(0, None)],
    "npu_chunk_scaled_dot_kkt": [(0, None)],
    "npu_fast_gelu_custom": [(0, None)],
    "npu_fast_gelu_custom_backward": [(0, None)],
    "npu_kda_gate_cumsum": [(0, None)],
    "npu_prepare_wy_repr_bwd": [(0, None), (1, None), (2, None), (3, None)],
    "npu_prepare_wy_repr_bwd_da": [(0, None)],
    "npu_prepare_wy_repr_bwd_full": [(0, None), (1, None), (2, None), (3, None)],
    "npu_recompute_w_u_fwd": [(0, None), (1, None)],
    "npu_solve_tri": [(0, None)],
}

def npu_chunk_bwd_dqkwg(q, k, v, g, h, dox, dh, dv, chunk_size, *, cu_seqlens=None, chunk_indices=None, w=None, g_gamma=None, scale=None, use_exp2=None, transpose_state_layout=None):
    return _call("npu_chunk_bwd_dqkwg", {
        "q": q,
        "k": k,
        "v": v,
        "g": g,
        "h": h,
        "dox": dox,
        "dh": dh,
        "dv": dv,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "w": w,
        "g_gamma": g_gamma,
        "scale": scale,
        "chunk_size": chunk_size,
        "use_exp2": use_exp2,
        "transpose_state_layout": transpose_state_layout,
    })

def npu_chunk_bwd_dv_local(q, k, d_o, g, scale, chunk_size, *, g_gamma=None, A=None, cu_seqlens=None, chunk_indices=None):
    return _call("npu_chunk_bwd_dv_local", {
        "q": q,
        "k": k,
        "d_o": d_o,
        "g": g,
        "g_gamma": g_gamma,
        "A": A,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "scale": scale,
        "chunk_size": chunk_size,
    })

def npu_chunk_gated_delta_rule_bwd_finalize(q, k, v, v_new, do, du, g, beta, h, dh, a, *, q_rstd=None, k_rstd=None, beta_raw=None, cu_seqlens=None, chunk_indices=None, scale=None, chunk_size=64, use_qk_l2_norm_in_kernel=False, use_beta_sigmoid_in_kernel=False, use_gate_in_kernel=False, state_v_first=False, use_exp2=True):
    return _call("npu_chunk_gated_delta_rule_bwd_finalize", {
        "q": q,
        "k": k,
        "v": v,
        "v_new": v_new,
        "do": do,
        "du": du,
        "g": g,
        "beta": beta,
        "h": h,
        "dh": dh,
        "a": a,
        "q_rstd": q_rstd,
        "k_rstd": k_rstd,
        "beta_raw": beta_raw,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "scale": scale,
        "chunk_size": chunk_size,
        "use_qk_l2_norm_in_kernel": use_qk_l2_norm_in_kernel,
        "use_beta_sigmoid_in_kernel": use_beta_sigmoid_in_kernel,
        "use_gate_in_kernel": use_gate_in_kernel,
        "state_v_first": state_v_first,
        "use_exp2": use_exp2,
    })

def npu_chunk_kda_bwd_intra(q, k, gk, beta, dAqk, dAkk, dq, dk, db, dg, *, cu_seqlens=None, chunk_indices=None, chunk_size=64, safe_gate=True, layout="BSND"):
    return _call("npu_chunk_kda_bwd_intra", {
        "q": q,
        "k": k,
        "gk": gk,
        "beta": beta,
        "dAqk": dAqk,
        "dAkk": dAkk,
        "dq": dq,
        "dk": dk,
        "db": db,
        "dg": dg,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
        "safe_gate": safe_gate,
        "layout": layout,
    })

def npu_chunk_local_cumsum(g, chunk_size, *, cu_seqlens=None, chunk_indices=None, reverse=False, scale=1.0, head_first=True, output_dtype="float32"):
    return _call("npu_chunk_local_cumsum", {
        "g": g,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
        "reverse": reverse,
        "scale": scale,
        "head_first": head_first,
        "output_dtype": output_dtype,
    })

def npu_chunk_scaled_dot_kkt(k, g, beta, *, cu_seqlens=None, chunk_indices=None, chunk_size=64):
    return _call("npu_chunk_scaled_dot_kkt", {
        "k": k,
        "g": g,
        "beta": beta,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
    })

def npu_fast_gelu_custom(self):
    return _call("npu_fast_gelu_custom", {
        "self": self,
    })

def npu_fast_gelu_custom_backward(grad, self):
    return _call("npu_fast_gelu_custom_backward", {
        "grad": grad,
        "self": self,
    })

def npu_kda_gate_cumsum(g, chunk_size, *, A_log=None, dt_bias=None, cu_seqlens=None, use_gate_in_kernel=None, safe_gate=None, lower_bound=None):
    return _call("npu_kda_gate_cumsum", {
        "g": g,
        "A_log": A_log,
        "dt_bias": dt_bias,
        "cu_seqlens": cu_seqlens,
        "chunk_size": chunk_size,
        "use_gate_in_kernel": use_gate_in_kernel,
        "safe_gate": safe_gate,
        "lower_bound": lower_bound,
    })

def npu_prepare_wy_repr_bwd(k, v, beta, A, dw, du, g, chunk_size, *, cu_seqlens=None, chunk_indices=None):
    return _call("npu_prepare_wy_repr_bwd", {
        "k": k,
        "v": v,
        "beta": beta,
        "A": A,
        "dw": dw,
        "du": du,
        "g": g,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
    })

def npu_prepare_wy_repr_bwd_da(k, v, beta, A, dw, du, g, *, cu_seqlens=None, chunk_indices=None, chunk_size=None):
    return _call("npu_prepare_wy_repr_bwd_da", {
        "k": k,
        "v": v,
        "beta": beta,
        "A": A,
        "dw": dw,
        "du": du,
        "g": g,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
    })

def npu_prepare_wy_repr_bwd_full(k, v, beta, A, dA, dw, du, g, chunk_size, *, cu_seqlens=None, chunk_indices=None):
    return _call("npu_prepare_wy_repr_bwd_full", {
        "k": k,
        "v": v,
        "beta": beta,
        "A": A,
        "dA": dA,
        "dw": dw,
        "du": du,
        "g": g,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
    })

def npu_recompute_w_u_fwd(k, v, beta, A, chunk_size, *, g=None, gk=None, cu_seqlens=None, chunk_indices=None):
    return _call("npu_recompute_w_u_fwd", {
        "k": k,
        "v": v,
        "beta": beta,
        "A": A,
        "g": g,
        "gk": gk,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "chunk_size": chunk_size,
    })

def npu_solve_tri(x, *, cu_seqlens=None, chunk_indices=None, layout="bsnd"):
    return _call("npu_solve_tri", {
        "x": x,
        "cu_seqlens": cu_seqlens,
        "chunk_indices": chunk_indices,
        "layout": layout,
    })

__all__ = [
    "npu_chunk_bwd_dqkwg",
    "npu_chunk_bwd_dv_local",
    "npu_chunk_gated_delta_rule_bwd_finalize",
    "npu_chunk_kda_bwd_intra",
    "npu_chunk_local_cumsum",
    "npu_chunk_scaled_dot_kkt",
    "npu_fast_gelu_custom",
    "npu_fast_gelu_custom_backward",
    "npu_kda_gate_cumsum",
    "npu_prepare_wy_repr_bwd",
    "npu_prepare_wy_repr_bwd_da",
    "npu_prepare_wy_repr_bwd_full",
    "npu_recompute_w_u_fwd",
    "npu_solve_tri",
]
